"""Generate genesis, validator keys and static-nodes.json with Besu's own tool.

The Besu step is injected (`Generator`), so the file logic can be tested without Docker.
"""

import json
import shutil
import subprocess
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from eth_account import Account

from src.adapters.firefly_files import write_firefly_files
from src.core.network.enode import NetworkAddressing, static_nodes
from src.core.network.genesis import build_qbft_config
from src.core.network.validators import extra_data_lists_all, sort_validators
from src.core.network.wallets import Wallet, build_wallets_document

BESU_IMAGE = "hyperledger/besu:26.8.1"
VALIDATOR_COUNT = 4
WALLET_NAMES = ("admin", "anson", "beatrice")

# Writes what `besu operator generate-blockchain-config` writes: (config file, output dir).
Generator = Callable[[Path, Path], None]

_README = """\
# network-config

Generated by `python scripts/stack.py init`. Everything here is **demo only**.

- `genesis.json`: QBFT genesis, chainId 20260916, zero gas.
- `validator-keys/validator-N/`: `key`, `key.pub` and `address.txt` for each of the 4 validators,
  numbered by sorted address.
- `static-nodes.json`: the 4 validator enodes on their fixed IPs.
- `wallets.json`: the `admin`, `anson` and `beatrice` demo wallets (address and private key).
- `firefly/`: FireFly core, evmconnect and signer config, and `signer-data/` with a keystore for
  each wallet (the signer's password is in the same folder).

The keys and wallets are throwaway credentials for a local network with no real value, and they
are committed on purpose (plan D-10). Never reuse them anywhere else.
"""


class AlreadyInitialisedError(Exception):
    """network-config already holds generated files and --force was not given."""


class GenerationError(Exception):
    """Besu's output was missing or inconsistent."""


@dataclass(frozen=True)
class InitResult:
    validator_addresses: list[str]
    files: list[Path]


def docker_generator(image: str = BESU_IMAGE) -> Generator:
    """Run the Besu tool in a container. The output folder must not exist yet."""

    def run(config_file: Path, out_dir: Path) -> None:
        work = config_file.parent
        command = [
            "docker", "run", "--rm", "-v", f"{work}:/cfg", image,
            "operator", "generate-blockchain-config",
            f"--config-file=/cfg/{config_file.name}",
            f"--to=/cfg/{out_dir.name}",
            "--private-key-file-name=key",
        ]  # fmt: skip
        proc = subprocess.run(command, capture_output=True, text=True, timeout=300, check=False)
        # Besu prints "Output directory already exists" even though it wrote the files (Phase 0).
        noise = "Output directory already exists" in proc.stdout + proc.stderr
        if proc.returncode != 0 and not (noise and (out_dir / "genesis.json").is_file()):
            raise GenerationError(f"Besu exited with {proc.returncode}: {proc.stderr.strip()}")

    return run


def generate_wallets(names: tuple[str, ...] = WALLET_NAMES) -> list[Wallet]:
    """Create one random demo wallet per name."""
    wallets = []
    for name in names:
        account = Account.create()
        wallets.append(Wallet(name, str(account.address).lower(), "0x" + account.key.hex()))
    return wallets


def init_network(
    network_dir: Path,
    *,
    generator: Generator,
    validator_count: int = VALIDATOR_COUNT,
    addressing: NetworkAddressing | None = None,
    force: bool = False,
) -> InitResult:
    """Generate the network files into `network_dir`. Refuses to overwrite without `force`."""
    addressing = addressing or NetworkAddressing()
    targets = [
        network_dir / "genesis.json",
        network_dir / "validator-keys",
        network_dir / "static-nodes.json",
        network_dir / "wallets.json",
        network_dir / "firefly",
    ]
    if not force and any(t.exists() for t in targets):
        raise AlreadyInitialisedError(
            f"{network_dir} already holds generated files. Use --force to regenerate them."
        )

    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        config_file = work / "qbft-config.json"
        config_file.write_text(json.dumps(build_qbft_config(validator_count)), encoding="utf-8")
        out_dir = work / "out"
        generator(config_file, out_dir)
        keys = _read_keys(out_dir, validator_count)
        genesis_bytes = (out_dir / "genesis.json").read_bytes()
        genesis = json.loads(genesis_bytes)
        if not extra_data_lists_all(genesis.get("extraData", ""), list(keys)):
            raise GenerationError("genesis extraData does not list all validator addresses")
        wallets = generate_wallets()
        return _write(network_dir, genesis_bytes, keys, addressing, wallets, force)


def _read_keys(out_dir: Path, count: int) -> dict[str, tuple[bytes, bytes]]:
    key_folders = sorted((out_dir / "keys").glob("0x*")) if (out_dir / "keys").is_dir() else []
    if len(key_folders) != count:
        raise GenerationError(f"expected {count} validator keys, found {len(key_folders)}")
    by_address = {
        folder.name: ((folder / "key").read_bytes(), (folder / "key.pub").read_bytes())
        for folder in key_folders
    }
    return {address: by_address[address] for address in sort_validators(by_address)}


def _write(
    network_dir: Path,
    genesis: bytes,
    keys: dict[str, tuple[bytes, bytes]],
    addressing: NetworkAddressing,
    wallets: list[Wallet],
    force: bool,
) -> InitResult:
    network_dir.mkdir(parents=True, exist_ok=True)
    keys_dir = network_dir / "validator-keys"
    if force and keys_dir.exists():
        shutil.rmtree(keys_dir)
    files: list[Path] = []
    for number, (address, (private, public)) in enumerate(keys.items(), start=1):
        folder = keys_dir / f"validator-{number}"
        folder.mkdir(parents=True)
        for name, content in (("key", private), ("key.pub", public)):
            (folder / name).write_bytes(content)
            files.append(folder / name)
        (folder / "address.txt").write_text(address + "\n", encoding="utf-8", newline="\n")
        files.append(folder / "address.txt")

    (network_dir / "genesis.json").write_bytes(genesis)
    files.append(network_dir / "genesis.json")

    public_keys = [public.decode("utf-8").strip() for _, public in keys.values()]
    nodes_file = network_dir / "static-nodes.json"
    nodes_file.write_text(
        json.dumps(static_nodes(public_keys, addressing), indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    files.append(nodes_file)

    wallets_file = network_dir / "wallets.json"
    wallets_file.write_text(
        json.dumps(build_wallets_document(wallets), indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    files.append(wallets_file)

    files.extend(write_firefly_files(network_dir / "firefly", wallets))

    readme = network_dir / "README.md"
    readme.write_text(_README, encoding="utf-8", newline="\n")
    files.append(readme)
    return InitResult(validator_addresses=list(keys), files=files)
