log:
  level: debug
http:
  port: 5000
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5000
admin:
  port: 5101
  address: 0.0.0.0
  enabled: true
spi:
  port: 5101
  address: 0.0.0.0
  enabled: true
event:
  dbevents:
    bufferSize: 10000
plugins:
  database:
  - name: database0
    type: postgres
    postgres:
      url: postgres://postgres:f1refly@postgres:5432?sslmode=disable
      migrations:
        auto: true
  blockchain:
  - name: blockchain0
    type: ethereum
    ethereum:
      ethconnect:
        url: http://evmconnect:5008
        topic: "0"
namespaces:
  default: default
  predefined:
  - name: default
    description: Default predefined namespace
    defaultKey: 0x86B6f13762a3E9208C6D87D882eAaB25fDE69E9d
    plugins: [database0, blockchain0]
    multiparty:
      enabled: false
